version: '3'
services:
  restic:
    build: .
    container_name: restic_container
    image: restic_debian
    stdin_open: true  # Voor interactiviteit
    tty: true         # Houdt de terminal open
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - ./imdb-postgresql:/imdb-postgresql          # Locatie voor de sample database
      - ./backups:/backups               # Locatie voor restic back-ups
      - ./sql_operations:/sql_operations  # Locatie voor SQL scripts
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#    volumes:
#      - pgdata:/var/lib/postgresql/data  # Opslag voor de PostgreSQL data
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  pgdata:
